version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
#    ports:
#      - '8090:8090'

  db:
    image: postgres:17.4-alpine
    container_name: postgres_17.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    networks:
      db-backend:
        aliases:
          - db.db-backend

volumes:
  postgres-volume:

networks:
  db-backend:
