spring:
#  server.port: 8080
  main:
    banner-mode: off
  application:
    name: spring-database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'

data:
  criticalValue: 'VALUE'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: ru.itmo.jpa.controller