spring:
  main:
    banner-mode: off
  application:
    name: spring-database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
#    driver-class-name: org.postgresql.Driver